# Generated by ShinyGenerator v0.0.1
# Please edit background and other relevant sections

# load packages ----
library("shiny")
library("shinydashboard")
library("dplyr")
library("readr")
library("here")
library("DT")
library("CDMUtilities")
library("shinyWidgets")
library("tidyr")
library("plotly")
library("shinycssloaders")
library("IncidencePrevalence")
library("ggplot2")

# read results from data folder ----
files <- list.files(here("data"), full.names = TRUE)
cdmSnapshot <- NULL
incidenceEstimates <- NULL
cohortDetails <- NULL
for (file in files) {
  name <- basename(file)
  x <- read_csv(file, show_col_types = FALSE)
  if (grepl("snapshot", file)) {
    cdmSnapshot <- union_all(cdmSnapshot, x)
  } else if (grepl("incidence", file)) {
    incidenceEstimates <- union_all(incidenceEstimates, x)
  } else if (grepl("counts", file)) {
    cohortDetails <- bind_rows(cohortDetails, x)
  }
}
cdmSnapshot <- cdmSnapshot %>% mutate(result_type = "CDM snapshot")
incidenceEstimates <- incidenceEstimates %>% 
  mutate(result_type = "Incidence estimates") %>%
  mutate(analysis_outcome_washout = 0)

# ui shiny ----
ui <- dashboardPage(
  dashboardHeader(title = "Menu"),
  ## menu ----
  dashboardSidebar(
    sidebarMenu(
      menuItem(
        text = "Background",
        tabName = "background"
      ),
      menuItem(
        text = "Database details",
        tabName = "database_details",
        menuSubItem(
          text = "CDM snapshot",
          tabName = "cdm_snapshot"
        )
      ),
      menuItem(
        text = "Cohort details",
        tabName = "cohort_details",
        menuSubItem(
          text = "Cohort count",
          tabName = "cohort_count"
        ),
        menuSubItem(
          text = "Cohort attrition",
          tabName = "cohort_attrition"
        )
      ),
      menuItem(
        text = "Incidence",
        tabName = "incidence",
        menuSubItem(
          text = "Incidence estimates",
          tabName = "incidence_estimates"
        )
      )
    )
  ),
  ## body ----
  dashboardBody(
    tabItems(
      ### background ----
      tabItem(
        tabName = "background",
        h3("Please edit this part in the file app.R"),
        h3("STUDY TITLE"),
        h4("Identifier: PX-CX-XXX"),
        p("The main purposo of this study is to identify ..."),
        p("This shinyApp was generated automatically with ShinyGenerator")
      ),
      ### cdm_snapshot ----
      tabItem(
        tabName = "cdm_snapshot",
        h3("Database details"),
        p("See details of CDM snapshot for each database:"),
        DTOutput("cdm_snapshot_table")
      ),
      ### cohort_count ----
      tabItem(
        tabName = "cohort_count",
        h3("Cohort counts"),
        p("Cohort counts for each cohort of the present study"),
        div(
          style = "display: inline-block;vertical-align:top; width: 150px;",
          pickerInput(
            inputId = "cohort_count_cohort_table_name",
            label = "Cohort table name",
            choices = unique(cohortDetails$cohort_table_name),
            selected = unique(cohortDetails$cohort_table_name),
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3"),
            multiple = TRUE
          )
        ),
        div(
          style = "display: inline-block;vertical-align:top; width: 150px;",
          pickerInput(
            inputId = "cohort_count_count",
            label = "Count type",
            choices = c("Number records", "Number subjects"),
            selected = "Number records",
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3"),
            multiple = FALSE
          )
        ),
        div(
          style = "display: inline-block;vertical-align:top; width: 150px;",
          pickerInput(
            inputId = "cohort_count_cdm_name",
            label = "CDM name",
            choices = unique(cohortDetails$cdm_name),
            selected = unique(cohortDetails$cdm_name),
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3"),
            multiple = TRUE
          )
        ),
        div(
          style = "margin-bottom: 20px;",
          downloadButton("cohort_count_download_table", "Download current counts")
        ),
        DTOutput("cohort_count_table") %>% withSpinner()
      ),
      ### cohort_attrition ----
      tabItem(
        tabName = "cohort_attrition",
        h3("Cohort attrition"),
        p("See the attrition for each cohort of the present study"),
        div(
          style = "display: inline-block;vertical-align:top; width: 150px;",
          pickerInput(
            inputId = "cohort_attrition_cdm_name",
            label = "CDM name",
            choices = unique(cohortDetails$cdm_name),
            selected = unique(cohortDetails$cdm_name),
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3"),
            multiple = FALSE
          )
        ),
        div(
          style = "display: inline-block;vertical-align:top; width: 200px;",
          pickerInput(
            inputId = "cohort_attrition_cohort_name",
            label = "Cohort table and cohort name",
            choices = cohortDetails %>%
              mutate(cohort_name = paste0(cohort_table_name, ": ", cohort_name)) %>%
              select(cohort_name) %>% distinct() %>% pull(),
            selected = cohortDetails %>%
              head(1) %>%
              mutate(cohort_name = paste0(cohort_table_name, ": ", cohort_name)) %>%
              pull(cohort_name),
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3"),
            multiple = FALSE
          )
        ),
        div(
          style = "margin-bottom: 20px;",
          downloadButton("cohort_attrition_download_table", "Download current attrition")
        ),
        DTOutput("cohort_attrition_table") %>% withSpinner()
      ),
      ### incidence_estimates ----
      tabItem(
        tabName = "incidence_estimates",
        h3("Incidence estimates"),
        p("Incidence estimates are shown below, please select configuration to filter them:"),
        p("Database and study outcome"),
        div(
          style = "display: inline-block;vertical-align:top; width: 150px;",
          pickerInput(
            inputId = "incidence_estimates_cdm_name",
            label = "CDM name",
            choices = unique(incidenceEstimates$cdm_name),
            selected = unique(incidenceEstimates$cdm_name),
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3"),
            multiple = TRUE
          )
        ),
        div(
          style = "display: inline-block;vertical-align:top; width: 150px;",
          pickerInput(
            inputId = "incidence_estimates_outcome_cohort_name",
            label = "Outcome name",
            choices = unique(incidenceEstimates$outcome_cohort_name),
            selected = unique(incidenceEstimates$outcome_cohort_name),
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3"),
            multiple = TRUE
          )
        ),
        p("Denominator population settings"),
        div(
          style = "display: inline-block;vertical-align:top; width: 150px;",
          pickerInput(
            inputId = "incidence_estimates_denominator_target_cohort_name",
            label = "Strata",
            choices = unique(incidenceEstimates$denominator_target_cohort_name),
            selected = unique(incidenceEstimates$denominator_target_cohort_name),
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3"),
            multiple = TRUE
          )
        ),
        div(
          style = "display: inline-block;vertical-align:top; width: 150px;",
          pickerInput(
            inputId = "incidence_estimates_denominator_age_group",
            label = "Age group",
            choices = unique(incidenceEstimates$denominator_age_group),
            selected = unique(incidenceEstimates$denominator_age_group),
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3"),
            multiple = TRUE
          )
        ),
        div(
          style = "display: inline-block;vertical-align:top; width: 150px;",
          pickerInput(
            inputId = "incidence_estimates_denominator_sex",
            label = "Sex",
            choices = unique(incidenceEstimates$denominator_sex),
            selected = unique(incidenceEstimates$denominator_sex),
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3"),
            multiple = TRUE
          )
        ),
        div(
          style = "display: inline-block;vertical-align:top; width: 150px;",
          pickerInput(
            inputId = "incidence_estimates_denominator_days_prior_observation",
            label = "Days prior observation",
            choices = unique(incidenceEstimates$denominator_days_prior_observation),
            selected = unique(incidenceEstimates$denominator_days_prior_observation),
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3"),
            multiple = TRUE
          )
        ),
        div(
          style = "display: inline-block;vertical-align:top; width: 150px;",
          pickerInput(
            inputId = "incidence_estimates_denominator_start_date",
            label = "Start date",
            choices = unique(incidenceEstimates$denominator_start_date),
            selected = unique(incidenceEstimates$denominator_start_date),
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3"),
            multiple = TRUE
          )
        ),
        div(
          style = "display: inline-block;vertical-align:top; width: 150px;",
          pickerInput(
            inputId = "incidence_estimates_denominator_end_date",
            label = "End date",
            choices = unique(incidenceEstimates$denominator_end_date),
            selected = unique(incidenceEstimates$denominator_end_date),
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3"),
            multiple = TRUE
          )
        ),
        p("Analysis settings"),
        div(
          style = "display: inline-block;vertical-align:top; width: 150px;",
          pickerInput(
            inputId = "incidence_estimates_analysis_outcome_washout",
            label = "Outcome washout",
            choices = unique(incidenceEstimates$analysis_outcome_washout),
            selected = unique(incidenceEstimates$analysis_outcome_washout),
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3"),
            multiple = TRUE
          )
        ),
        div(
          style = "display: inline-block;vertical-align:top; width: 150px;",
          pickerInput(
            inputId = "incidence_estimates_analysis_repeated_events",
            label = "Repeated events",
            choices = unique(incidenceEstimates$analysis_repeated_events),
            selected = unique(incidenceEstimates$analysis_repeated_events),
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3"),
            multiple = TRUE
          )
        ),
        div(
          style = "display: inline-block;vertical-align:top; width: 150px;",
          pickerInput(
            inputId = "incidence_estimates_analysis_complete_database_intervals",
            label = "Complete period",
            choices = unique(incidenceEstimates$analysis_complete_database_intervals),
            selected = unique(incidenceEstimates$analysis_complete_database_intervals),
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3"),
            multiple = TRUE
          )
        ),
        div(
          style = "display: inline-block;vertical-align:top; width: 150px;",
          pickerInput(
            inputId = "incidence_estimates_analysis_min_cell_count",
            label = "Minimum counts",
            choices = unique(incidenceEstimates$analysis_min_cell_count),
            selected = unique(incidenceEstimates$analysis_min_cell_count),
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3"),
            multiple = TRUE
          )
        ),
        p("Dates"),
        div(
          style = "display: inline-block;vertical-align:top; width: 150px;",
          pickerInput(
            inputId = "incidence_estimates_analysis_interval",
            label = "Interval",
            choices = unique(incidenceEstimates$analysis_interval),
            selected = unique(incidenceEstimates$analysis_interval),
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3"),
            multiple = TRUE
          )
        ),
        div(
          style = "display: inline-block;vertical-align:top; width: 150px;",
          pickerInput(
            inputId = "incidence_estimates_incidence_start_date",
            label = "Incidence start date",
            choices = unique(incidenceEstimates$incidence_start_date),
            selected = unique(incidenceEstimates$incidence_start_date),
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3"),
            multiple = TRUE
          )
        ),
        tabsetPanel(
          type = "tabs",
          tabPanel(
            "Table of estimates",
            downloadButton("incidence_estimates_download_table", "Download current estimates"),
            DTOutput("incidence_estimates_table") %>% withSpinner()
          ),
          tabPanel(
            "Plot of estimates",
            p("Plotting options"),
            div(
              style = "display: inline-block;vertical-align:top; width: 150px;",
              pickerInput(
                inputId = "incidence_estimates_plot_x",
                label = "x axis",
                choices = c("cdm_name", "outcome_cohort_name", "denominator_target_cohort_name", "denominator_age_group", "denominator_sex", "denominator_days_prior_observation", "denominator_start_date", "denominator_end_date", "analysis_outcome_washout", "analysis_repeated_events", "analysis_complete_database_intervals", "analysis_min_cell_count", "analysis_interval", "incidence_start_date"),
                selected = "incidence_start_date",
                list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3"),
                multiple = FALSE
              )
            ),
            div(
              style = "display: inline-block;vertical-align:top; width: 150px;",
              pickerInput(
                inputId = "incidence_estimates_plot_facet",
                label = "Facet by",
                choices = c("cdm_name", "outcome_cohort_name", "denominator_target_cohort_name", "denominator_age_group", "denominator_sex", "denominator_days_prior_observation", "denominator_start_date", "denominator_end_date", "analysis_outcome_washout", "analysis_repeated_events", "analysis_complete_database_intervals", "analysis_min_cell_count", "analysis_interval", "incidence_start_date"),
                selected = c("outcome_cohort_name", "cdm_name"),
                list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3"),
                multiple = TRUE
              )
            ),
            div(
              style = "display: inline-block;vertical-align:top; width: 150px;",
              pickerInput(
                inputId = "incidence_estimates_plot_colour",
                label = "Colour by",
                choices = c("cdm_name", "outcome_cohort_name", "denominator_target_cohort_name", "denominator_age_group", "denominator_sex", "denominator_days_prior_observation", "denominator_start_date", "denominator_end_date", "analysis_outcome_washout", "analysis_repeated_events", "analysis_complete_database_intervals", "analysis_min_cell_count", "analysis_interval", "incidence_start_date"),
                list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3"),
                multiple = TRUE
              )
            ),
            plotlyOutput(
              "incidence_estimates_plot",
              height = "800px"
            ) %>%
              withSpinner(),
            h4("Download figure"),
            div("height:", style = "display: inline-block; font-weight: bold; margin-right: 5px;"),
            div(
              style = "display: inline-block;",
              textInput("incidence_estimates_download_height", "", 10, width = "50px")
            ),
            div("cm", style = "display: inline-block; margin-right: 25px;"),
            div("width:", style = "display: inline-block; font-weight: bold; margin-right: 5px;"),
            div(
              style = "display: inline-block;",
              textInput("incidence_estimates_download_width", "", 20, width = "50px")
            ),
            div("cm", style = "display: inline-block; margin-right: 25px;"),
            div("dpi:", style = "display: inline-block; font-weight: bold; margin-right: 5px;"),
            div(
              style = "display: inline-block; margin-right:",
              textInput("incidence_estimates_download_dpi", "", 300, width = "50px")
            ),
            downloadButton("incidence_estimates_download_plot", "Download plot")
          )
        )
      )
    )
  )
)

# server shiny ----
server <- function(input, output, session) {
  ## cdm_snapshot ----
  output$cdm_snapshot_table <- renderDataTable({
    datatable(
      cdmSnapshot %>% select(-result_type),
      rownames = FALSE,
      extensions = "Buttons",
      options = list(scrollX = TRUE, scrollCollapse = TRUE)
    )
  })

  ## cohort_count ----
  ### get counts ----
  getCohortCount <- reactive({
    cohortDetails %>%
      mutate(reason_id = as.numeric(reason_id)) %>%
      filter(cdm_name %in% input$cohort_count_cdm_name) %>%
      filter(cohort_table_name %in% input$cohort_count_cohort_table_name) %>%
      group_by(cohort_name, cohort_table_name) %>%
      filter(reason_id == max(reason_id)) %>%
      ungroup() %>%
      select(cohort_table_name, cohort_name, cdm_name, value = !!toSnakeCase(input$cohort_count_count)) %>%
      mutate(value = suppressWarnings(as.numeric(value))) %>%
      pivot_wider(names_from = cdm_name, values_from = value)
  })
  ### download table ----
  output$cohort_count_download_table <- downloadHandler(
    filename = function() {
      "cohortCountTable.csv"
    },
    content = function(file) {
      write_csv(getCohortCount(), file)
    }
  )
  ### table count ----
  output$cohort_count_table <- renderDataTable({
    table <- getCohortCount()
    validate(need(nrow(table) > 0, "No results for selected inputs"))
    datatable(
      table,
      rownames = FALSE,
      extensions = "Buttons",
      options = list(scrollX = TRUE, scrollCollapse = TRUE)
    )
  })

  ## cohort_attrition ----
  ### get attrition ----
  getCohortAttrition <- reactive({
    cohortDetails %>%
      mutate(cohort_name = paste0(cohort_table_name, ": ", cohort_name)) %>%
      filter(cohort_name == input$cohort_attrition_cohort_name) %>%
      filter(cdm_name == input$cohort_attrition_cdm_name) %>%
      mutate(reason_id = as.numeric(reason_id)) %>%
      arrange(reason_id) %>%
      select(reason_id, reason, number_records, number_subjects, excluded_records, excluded_subjects)
  })
  ### download table ----
  output$cohort_attrition_download_table <- downloadHandler(
    filename = function() {
      "cohortAttritionTable.csv"
    },
    content = function(file) {
      write_csv(getCohortAttrition(), file)
    }
  )
  ### table count ----
  output$cohort_attrition_table <- renderDataTable({
    table <- getCohortAttrition()
    validate(need(nrow(table) > 0, "No results for selected inputs"))
    datatable(
      table,
      rownames = FALSE,
      extensions = "Buttons",
      options = list(scrollX = TRUE, scrollCollapse = TRUE, ordering = F)
    )
  })

  ## incidence_estimates ----
  ### get estimates ----
  getIncidenceEstimates <- reactive({
    incidenceEstimates %>%
      filter(cdm_name %in% input$incidence_estimates_cdm_name) %>%
      filter(outcome_cohort_name %in% input$incidence_estimates_outcome_cohort_name) %>%
      filter(denominator_target_cohort_name %in% input$incidence_estimates_denominator_target_cohort_name) %>%
      filter(denominator_age_group %in% input$incidence_estimates_denominator_age_group) %>%
      filter(denominator_sex %in% input$incidence_estimates_denominator_sex) %>%
      # filter(denominator_days_prior_observation %in% input$incidence_estimates_denominator_days_prior_observation) %>%
      # filter(denominator_start_date %in% input$incidence_estimates_denominator_start_date) %>%
      # filter(denominator_end_date %in% input$incidence_estimates_denominator_end_date) %>%
      # filter(analysis_outcome_washout %in% input$incidence_estimates_analysis_outcome_washout) %>%
      # filter(analysis_repeated_events %in% input$incidence_estimates_analysis_repeated_events) %>%
      # filter(analysis_complete_database_intervals %in% input$incidence_estimates_analysis_complete_database_intervals) %>%
      # filter(analysis_min_cell_count %in% input$incidence_estimates_analysis_min_cell_count) %>%
      # filter(analysis_interval %in% input$incidence_estimates_analysis_interval) %>%
      # filter(incidence_start_date %in% input$incidence_estimates_incidence_start_date) %>%
      mutate(
        person_years = round(suppressWarnings(as.numeric(person_years))),
        person_days = round(suppressWarnings(as.numeric(person_days))),
        n_events = round(suppressWarnings(as.numeric(n_events))),
        incidence_100000_pys = round(suppressWarnings(as.numeric(incidence_100000_pys))),
        incidence_100000_pys_95CI_lower = round(suppressWarnings(as.numeric(incidence_100000_pys_95CI_lower))),
        incidence_100000_pys_95CI_upper = round(suppressWarnings(as.numeric(incidence_100000_pys_95CI_upper)))
      )
  })
  ### download table ----
  output$incidence_estimates_download_table <- downloadHandler(
    filename = function() {
      "incidenceEstimatesTable.csv"
    },
    content = function(file) {
      write_csv(getIncidenceEstimates(), file)
    }
  )
  ### table estimates ----
  output$incidence_estimates_table <- renderDataTable({
    table <- getIncidenceEstimates()
    validate(need(nrow(table) > 0, "No results for selected inputs"))
    table <- table %>%
      mutate(incidence_100000_pys = paste0(
        incidence_100000_pys, " (", incidence_100000_pys_95CI_lower, " to ",
        incidence_100000_pys_95CI_upper, " )"
      )) %>%
      select(cdm_name, outcome_cohort_name, denominator_target_cohort_name, denominator_age_group, denominator_sex, denominator_days_prior_observation, denominator_start_date, denominator_end_date, analysis_outcome_washout, analysis_repeated_events, analysis_complete_database_intervals, analysis_min_cell_count, analysis_interval, incidence_start_date, n_events, n_persons, person_years, incidence_100000_pys)
    datatable(
      table,
      rownames = FALSE,
      extensions = "Buttons",
      options = list(scrollX = TRUE, scrollCollapse = TRUE)
    )
  })
  ### make plot ----
  plotIncidenceEstimates <- reactive({
    table <- getIncidenceEstimates()
    validate(need(nrow(table) > 0, "No results for selected inputs"))
    class(table) <- c("IncidenceResult", "IncidencePrevalenceResult", class(table))
    plotIncidence(
      table,
      x = input$incidence_estimates_plot_x,
      ylim = c(0, NA),
      ribbon = TRUE,
      facet = input$incidence_estimates_plot_facet,
      colour = input$incidence_estimates_plot_colour,
      colour_name = paste0(input$incidence_estimates_plot_colour, collapse = "; ")
    )
  })
  ### download plot ----
  output$incidence_estimates_download_plot <- downloadHandler(
    filename = function() {
      "incidenceEstimatesPlot.png"
    },
    content = function(file) {
      ggsave(
        file,
        plotIncidenceEstimates(),
        width = as.numeric(input$incidence_estimates_download_width),
        height = as.numeric(input$incidence_estimates_download_height),
        dpi = as.numeric(input$incidence_estimates_download_dpi),
        units = "cm"
      )
    }
  )
  ### plot ----
  output$incidence_estimates_plot <- renderPlotly({
    plotIncidenceEstimates()
  })
}

# run shiny ----
shinyApp(ui, server)
